added testing for login screen
anf38/CapstoneRecipes pull request #5
Opened 2024-03-10 17:43 UTC by Darkflair

2024-03-10 18:28 UTC, TomaszTB requested changes

2024-03-10 18:28 UTC, TomaszTB commented on app/build.gradle
> +     androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
This is nitpicky, but could you remove the extra space here?

2024-03-10 18:28 UTC, TomaszTB commented on app/src/androidTest/java/com/example/pantrypal/LoginTest.java
> +import androidx.test.core.app.ActivityScenario;
We've got a lot of unused imports here. You can run Ctrl + Alt + O to format the imports, which will also remove the unused ones.

2024-03-10 18:28 UTC, TomaszTB commented on app/src/androidTest/java/com/example/pantrypal/LoginTest.java
> +@RunWith(AndroidJUnit4.class)
The `AndroidJUnit4` used here is deprecated. Probably shouldn't use it then. Fortunately there seems to be a drop-in replacement for it, so it should only require changing an import statement (maybe some change to the Gradle file?). Take a look here: https://developer.android.com/reference/androidx/test/runner/AndroidJUnit4

2024-03-10 18:28 UTC, TomaszTB commented on app/src/androidTest/java/com/example/pantrypal/LoginTest.java
All the tests fail for me. Are there some prerequisites to running the tests that I'm missing?

2024-03-11 15:55 UTC, TomaszTB approved these changes
Seems great to me!

2024-03-18 16:39 UTC, anf38 commented
everything works well for me!

2024-03-18 16:45 UTC, merged